#!/bin/sh
rm /var/run/*.pid
/etc/init.d/cron start
# PRODUCTION
#python3 -m gunicorn --config gunicorn.conf.py "tidbyt_manager:create_app()"

# FLASK DEVELOPMENT
FLASK_APP=tidbyt_manager FLASK_DEBUG=1 flask run --host=0.0.0.0 --port=8000
