-- DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS device;

-- CREATE TABLE user (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     username TEXT UNIQUE NOT NULL,
--     password TEXT NOT NULL
-- );

CREATE TABLE device (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    owner_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    api_id TEXT NOT NULL,
    api_key TEXT NOT NULL,
    notes TEXT,
    FOREIGN KEY (owner_id) REFERENCES user (id)
);